name: Auto Label
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto-label:
    name: Auto Label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: banyan/auto-label@1.2
        if: github.repository.fork == false
        env:
          GITHUB_TOKEN: "${{ contains(secrets, 'GEN3_RELEASE_GH_TOKEN') ? secrets.GEN3_RELEASE_GH_TOKEN : 'ignore' }}"
