name: Auto Label
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto-label:
    name: Auto Label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: banyan/auto-label@1.2
        if: ${{ github.event.pull_request.head.repo.fork }} == false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
