name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.13.1"
        if: github.repository.fork == false
        env:
          GITHUB_TOKEN: "${{ contains(secrets, 'GEN3_RELEASE_GH_TOKEN') && secrets.GEN3_RELEASE_GH_TOKEN || 'ignore' }}"
